# Generated by Django 3.0.6 on 2020-06-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('', 'Select your Gender'), ('M', 'Male'), ('F', 'Female')], default='M', max_length=255, verbose_name='gender'),
        ),
    ]
