# Generated by Django 3.0.6 on 2020-06-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_main', '0002_auto_20200620_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(default='M', max_length=255),
        ),
    ]
