# Generated by Django 3.0.6 on 2020-06-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_main', '0004_auto_20200620_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnotification',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
