# Generated by Django 3.0.6 on 2020-06-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_main', '0005_auto_20200621_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
