# Generated by Django 3.1 on 2020-09-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
