# Generated by Django 3.1 on 2020-09-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_main', '0003_auto_20200907_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafffeedback',
            name='feedback_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
