# Generated by Django 3.1 on 2020-09-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_main', '0005_auto_20200907_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stat',
            field=models.CharField(choices=[('R', 'Regular'), ('I', 'Irregular'), ('G', 'Graduate'), ('D', 'DROPPED')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.CharField(choices=[('', '-Select Year Level-'), ('I', 'First Year'), ('II', 'Second Year'), ('III', 'Third Year'), ('IV', 'Fourth Year'), ('V', 'Fifth Year'), ('PG', 'Post Graduate')], max_length=3),
        ),
    ]
