# Generated by Django 3.1 on 2020-09-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_main', '0006_auto_20200917_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafffeedback',
            name='date_replied',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
