# Generated by Django 3.1 on 2020-09-18 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sms_main', '0007_stafffeedback_date_replied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereportstaff',
            name='leave_date',
        ),
        migrations.AddField(
            model_name='leavereportstaff',
            name='leave_end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavereportstaff',
            name='leave_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
